// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "gitee.com/cloud-mall/app/api/internal/handler/user"
	"gitee.com/cloud-mall/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/login",
					Handler: user.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/list",
					Handler: user.GetUserListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/repo/list",
					Handler: user.GetRepoListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/goods/list",
					Handler: user.GetGoodsListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
